import { motion } from 'framer-motion';
import { AlertTriangle, Compass, Lightbulb, Sparkles, Target } from 'lucide-react';
import { useEffect } from 'react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { LineSkeleton } from '@/components/feedback/Skeletons';
import { apiErrorMessage } from '@/lib/api/axios';
import { useInsights } from '../api/workbenchApi';

function InsightBlock({
  icon,
  title,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl bg-background/60 p-4">
      <div className="mb-1.5 flex items-center gap-2 text-ink-soft">
        <span className="text-rose-deep">{icon}</span>
        <h4 className="text-sm font-medium">{title}</h4>
      </div>
      <div className="text-sm leading-relaxed text-ink">{children}</div>
    </div>
  );
}

export function InsightsPanel({ customerId }: { customerId: string }) {
  const insights = useInsights(customerId);

  // Generate once on mount.
  useEffect(() => {
    insights.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [customerId]);

  return (
    <Card>
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-gold-soft/60 text-gold-deep">
            <Sparkles className="h-4 w-4" />
          </span>
          <div>
            <h3 className="font-serif text-lg text-ink">AI Insights</h3>
            <p className="text-xs text-ink-muted">Generated by Llama 3.3 70B</p>
          </div>
        </div>
      </div>

      <div>
        {insights.isPending ? (
          <div className="space-y-4">
            <LineSkeleton lines={3} />
            <LineSkeleton lines={2} />
            <LineSkeleton lines={3} />
          </div>
        ) : insights.isError ? (
          <div className="rounded-2xl bg-rose-soft/30 p-4 text-sm text-ink-soft">
            <p>{apiErrorMessage(insights.error, 'Insights are unavailable right now.')}</p>
            <Button variant="secondary" size="sm" className="mt-3" onClick={() => insights.mutate()}>
              Retry
            </Button>
          </div>
        ) : insights.data ? (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="space-y-3"
          >
            <InsightBlock icon={<Compass className="h-4 w-4" />} title="Personality Summary">
              {insights.data.personalitySummary}
            </InsightBlock>
            <InsightBlock icon={<Target className="h-4 w-4" />} title="Relationship Priorities">
              <ul className="list-inside list-disc space-y-1">
                {insights.data.relationshipPriorities.map((p, i) => (
                  <li key={i}>{p}</li>
                ))}
              </ul>
            </InsightBlock>
            <InsightBlock icon={<AlertTriangle className="h-4 w-4" />} title="Potential Challenges">
              <ul className="list-inside list-disc space-y-1">
                {insights.data.potentialChallenges.map((p, i) => (
                  <li key={i}>{p}</li>
                ))}
              </ul>
            </InsightBlock>
            <InsightBlock icon={<Lightbulb className="h-4 w-4" />} title="Suggested Strategy">
              {insights.data.suggestedStrategy}
            </InsightBlock>
          </motion.div>
        ) : null}
      </div>
    </Card>
  );
}
